### ISSUE TITLE
Compound stats in MobStatViewer

### ISSUE THREAD

**Issue by ckx** [ckx/KouCoCoa#8]
Would be good to have some more "meaningful" stats in the MobStatViewer, particularly things like:

* Def adjusted HP (& mdef adjusted HP)
* aspd adjusted ATK
* Average ATK?

These are fields Pienne has already written a formula for, should be in the old StatView spreadsheet. Maybe investigate hiding/showing columns in DataGridView controls again while I'm at it.

**Comment by Pienne** [comment]
def adjusted HP: hp/(1-(def/100)
mdef adjusted HP: hp/(1-(def/100))
average ATK per hit = (max ATK (atk2?) - min ATK (atk1?))/2
DPS = average ATK per hit / adelay (1000 = 1 attack per second)

formula structure is right, but I may be using the wrong variables regarding ATK and adelay
